#pragma once

// TODO: Find actual channels.

#define SWERVE_FL_DRIVE_MOTOR 0
#define SWERVE_BL_DRIVE_MOTOR 1
#define SWERVE_BR_DRIVE_MOTOR 2
#define SWERVE_FR_DRIVE_MOTOR 3

#define SWERVE_FL_ROT_MOTOR 4
#define SWERVE_BL_ROT_MOTOR 5
#define SWERVE_BR_ROT_MOTOR 6
#define SWERVE_FR_ROT_MOTOR 7

#define SWERVE_FL_ROT_CAN_CODER 8
#define SWERVE_BL_ROT_CAN_CODER 9
#define SWERVE_BR_ROT_CAN_CODER 10
#define SWERVE_FR_ROT_CAN_CODER 11

#define ANALOG_GYRO 12
