#pragma once

#define SWERVE_FL_DRIVE_MOTOR 20
#define SWERVE_BL_DRIVE_MOTOR 22
#define SWERVE_BR_DRIVE_MOTOR 23
#define SWERVE_FR_DRIVE_MOTOR 21

#define SWERVE_FL_ROT_MOTOR 2
#define SWERVE_BL_ROT_MOTOR 4
#define SWERVE_BR_ROT_MOTOR 3
#define SWERVE_FR_ROT_MOTOR 1

#define SWERVE_FL_ROT_CAN_CODER 11
#define SWERVE_BL_ROT_CAN_CODER 12
#define SWERVE_BR_ROT_CAN_CODER 13
#define SWERVE_FR_ROT_CAN_CODER 10

#define ANALOG_GYRO 0